# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

AllPark.destroy_all
AllPark.reset_pk_sequence
VisitedPark.destroy_all
VisitedPark.reset_pk_sequence
FavoritedPark.destroy_all
FavoritedPark.reset_pk_sequence

AllPark.create(fullName: "Abraham Lincoln Birthplace National Historical Park", description: "For over a century people from around the world have come to rural Central Kentucky to honor the humble beginnings of our 16th president, Abraham Lincoln. His early life on Kentucky's frontier shaped his character and prepared him to lead the nation through Civil War. The country's first memorial to Lincoln, built with donations from young and old, enshrines the symbolic birthplace cabin.", contacts: "270-358-3137", entranceFees: "0.00", operatingHours: "9:00AM - 5:00PM", addresses: "2995 Lincoln Farm Road, Hodgenville, KY 42748")
AllPark.create(fullName: "Acadia National Park", description: "Acadia National Park protects the natural beauty of the highest rocky headlands along the Atlantic coastline of the United States, an abundance of habitats, and a rich cultural heritage. At 3.5 million visits a year, it's one of the top 10 most-visited national parks in the United States. Visitors enjoy 27 miles of historic motor roads, 158 miles of hiking trails, and 45 miles of carriage roads.", contacts: "207-288-3338", entranceFees: "15.00", operatingHours: "All Day", addresses: "25 Visitor Center Road, Bar Harbor, ME 04609")
AllPark.create(fullName: "Adams National Historical Park", description: "From the sweet little farm at the foot of Penn’s Hill to the gentleman’s country estate at Peace field, Adams National Historical Park is the story of “heroes, statesman, philosophers … and learned women” whose ideas and actions helped to transform thirteen disparate colonies into one united nation.", contacts: "617-773-1177", entranceFees: "15.00", operatingHours: "10:00AM - 4:00PM", addresses: "1250 Hancock Street, Quincy, MA 02169")
AllPark.create(fullName: "African American Civil War Memorial", description: "Over 200,000 African-American soldiers and sailors served in the U.S. Army and Navy during the Civil War. Their service helped to end the war and free over four million slaves. The African American Civil War Memorial honors their service and sacrifice.", contacts: "202-426-6841", entranceFees: "0.00", operatingHours: "All Day", addresses: "1925 Vermont Avenue Northwest, Washington, DC 20001")
AllPark.create(fullName: "African Burial Ground National Monument", description: "African Burial Ground is the oldest and largest known excavated burial ground in North America for both free and enslaved Africans. It protects the historic role slavery played in building New York.", contacts: "212-238-4367", entranceFees: "0.00", operatingHours: "10:00AM - 4:00PM", addresses: "African Burial Ground National Monument, New York, NY 10007")
AllPark.create(fullName: "Agate Fossil Beds National Monument", description: "In the early 1900s, paleontologists unearthed the Age of Mammals when they found full skeletons of extinct Miocene mammals in the hills of Nebraska -- species previously only known through fragments. At the same time, an age of friendship began between rancher James Cook and Chief Red Cloud of the Lakota. These two unprecedented events are preserved and protected here... at Agate Fossil Beds.", contacts: "308-665-4113", entranceFees: "0.00", operatingHours: "Sunrise to Sunset", addresses: "301 River Road, Harrison, NE 69346")
AllPark.create(fullName: "Ala Kahakai National Historic Trail", description: "Established in 2000 to preserve, protect and interpret traditional Native Hawaiian culture and natural resources, Ala Kahakai National Historic Trail is a 175 mile corridor encompassing a network of culturally and historically significant trails. This trail by the sea traverses wahi pana (storied landscapes), ancient Hawaiian sites and over 200 ahupuaʻa (traditional land divisions). Connect now!", contacts: "808-326-6012", entranceFees: "0.00", operatingHours: "Sunrise to Sunset", addresses: "73-4786 Kanalani Street, #14, Kailua-Kona, HI 96740")
AllPark.create(fullName: "Alagnak Wild River", description: "The headwaters of Alagnak Wild River lie within the rugged Aleutian Range of neighboring Katmai National Park and Preserve. Meandering west towards Bristol Bay and the Bering Sea, the Alagnak traverses the beautiful Alaska Peninsula, providing an unparalleled opportunity to experience the unique wilderness, wildlife, and cultural heritage of southwest Alaska.", contacts: "907-246-3305", entranceFees: "0.00", operatingHours: "All Day", addresses: "1000 Silver St., Bldg. 603, King Salmon, AK, 99613")
AllPark.create(fullName: "Alaska Public Lands", description: "Alaska’s parks, forests, and refuges are rich and varied. The Alaska Public Lands Information Centers help visitors and residents to have meaningful, safe, enjoyable experiences on public lands, and encourages them to sustain the natural and cultural resources of Alaska. These centers provide trip-planning, interpretation, and education for all ages.", contacts: "907-644-3661", entranceFees: "0.00", operatingHours: "8:00AM - 6:00PM", addresses: "605 West 4th Avenue, Anchorage, AK 99501")
AllPark.create(fullName: "Alcatraz Island", description: "Alcatraz reveals stories of American incarceration, justice, and our common humanity. This small island was once a fort, a military prison, and a maximum security federal penitentiary. In 1969, the Indians of All Tribes occupied Alcatraz for 19 months in the name of freedom and Native American civil rights. We invite you to explore Alcatraz's complex history and natural beauty.", contacts: "415-561-4900", entranceFees: "39.90", operatingHours: "10:00AM - 9:00PM", addresses: "Alcatraz Island, San Francisco Bay, CA 94133")
AllPark.create(fullName: "Aleutian Islands World War II National Historic Area", description: "During World War II the remote Aleutian Islands, home to the Unangax̂ (Aleut) people for over 8,000 years, became a fiercely contested battleground in the Pacific. This thousand-mile-long archipelago saw invasion by Japanese forces, the occupation of two islands; a mass relocation of Unangax̂ civilians; a 15-month air war; and one of the deadliest battles in the Pacific Theater.", contacts: "907-644-3472", entranceFees: "6.00", operatingHours: "9:00AM - 10:00AM", addresses: "240 W 5th Avenue, Anchorage, AK 99501")
AllPark.create(fullName: "Alibates Flint Quarries National Monument", description: "13,000 years ago, this site was well-known by mammoth hunters as a source of flint for tools. Centuries passed but the colorful flint never lost its value and usefulness in the Texas Panhandle. Gain a sense of how integral this site was to the survival, commerce and culture of the High Plains. Visit Alibates Flint Quarries to see the many colors of the beautiful Alibates Flint.", contacts: "806-857-6680", entranceFees: "0.00", operatingHours: "9:00AM - 4:00PM", addresses: "37084 Alibates Rd, Potter County, TX 79036")
AllPark.create(fullName: "Allegheny Portage Railroad National Historic Site", description: "The first railroad to circumvent the Allegheny Mountains, the Allegheny Portage Railroad was the finishing piece of the Pennsylvania Mainline Canal. The Portage, opened in 1834, marking the first time that there was one, direct route between Philadelphia and Pittsburgh. All things to all people, it served merchants, passengers, slaves in pursuit of freedom, and soldiers from the Mexican War.", contacts: "814-886-6150", entranceFees: "0.00", operatingHours: "9:00AM - 5:00PM", addresses: "110 Federal Park Road, Gallitzin, PA 16641")
AllPark.create(fullName: "American Memorial Park", description: "American Memorial Park honors the American and Marianas people who gave their lives during the Marianas Campaign of World War II. At the park, memorials stand in tribute to the courage and sacrifice of the US Servicemen and Chamorro and Carolinian civilians who were killed in the battles between the United States and Japan that took place on Saipan, Tinian, and the Philippine Sea in 1944.", contacts: "670-234-7207", entranceFees: "0.00", operatingHours: "4:00AM - 2:00AM", addresses: "Beach Road, Saipan, MP 96950")
AllPark.create(fullName: "Amistad National Recreation Area", description: "An oasis in the desert, Amistad National Recreation Area consists of the US portion of the International Amistad Reservoir. Amistad, whose name comes from the Spanish word meaning friendship, is best known for excellent water-based recreation, camping, hiking, rock art viewing, and its rich cultural history. Amistad is also home to a wide variety of plant and animal life above and below the water.", contacts: "830-775-7491", entranceFees: "0.00", operatingHours: "All Day", addresses: "10477 Highway 90 West, Del Rio, TX 78840")
AllPark.create(fullName: "Anacostia Park", description: "Welcome to Anacostia Park, your neighborhood national park in the heart of Washington, DC! Enjoy exercise along the river trail or relax by the water, Anacostia Park is a breath of fresh air and a space to unwind amid a bustling city.", contacts: "202-472-3884", entranceFees: "0.00", operatingHours: "Sunrise to Sunset", addresses: "1900 Anacostia Drive, S.E., Washington, DC 20020")
AllPark.create(fullName: "Andersonville National Historic Site", description: "The Camp Sumter military prison at Andersonville was one of the largest Confederate military prisons during the Civil War. During the 14 months the prison existed, more than 45,000 Union soldiers were confined here. Of these, almost 13,000 died here. Today, Andersonville National Historic Site is a memorial to all American prisoners of war throughout the nation's history.", contacts: "229-924-0343", entranceFees: "0.00", operatingHours: "8:00AM - 5:00PM", addresses: "496 Cemetery Road, Andersonville, GA 31711")
AllPark.create(fullName: "Andrew Johnson National Historic Site", description: "Andrew Johnson's complex presidency (1865-69) illustrates the Constitution at work following the Civil War. As the President and Congress disagreed on Reconstruction methods, the Constitution served as their guide on balance of powers, vetoes, and impeachment. In the end, it evolved as a living document with pivotal amendments on freedom, citizenship, and voting rights - topics still vital today.", contacts: "423-638-3551", entranceFees: "0.00", operatingHours: "9:00AM - 4:00PM", addresses: "101 North College Street, Greeneville, TN 37743")
AllPark.create(fullName: "Aniakchak National Monument & Preserve", description: "Given its remote location and challenging weather conditions, Aniakchak is one of the most wild and least visited places in the National Park System. This landscape is a vibrant reminder of Alaska's location in the volcanically active Ring of Fire, as it is home to an impressive six mile (10 km) wide, 2,500 ft (762 m) deep caldera formed during a massive volcanic eruption 3,500 years ago.", contacts: "907-246-3305", entranceFees: "0.00", operatingHours: "All Day", addresses: "1000 Silver St., Bldg. 603, King Salmon, AK 99613")
AllPark.create(fullName: "Antietam National Battlefield", description: "23,000 soldiers were killed, wounded or missing after twelve hours of savage combat on September 17, 1862. The Battle of Antietam ended the Confederate Army of Northern Virginia's first invasion into the North and led Abraham Lincoln to issue the preliminary Emancipation Proclamation.", contacts: "301-432-5124", entranceFees: "0.00", operatingHours: "9:00AM - 5:00PM", addresses: "5831 Dunker Church Rd, Sharpsburg, MD 21782")
AllPark.create(fullName: "Apostle Islands National Lakeshore", description: "Imagine that moment, being in that perfect spot as the sun rises, and everything comes into focus. A rocky shoreline suddenly reflects the world around you. Waiting for you among the water, land, forests, and history is that moment. How will the islands inspire you?", contacts: "715-779-3397", entranceFees: "0.00", operatingHours: "All Day", addresses: "415 Washington Avenue, Bayfield, WI 54814")
AllPark.create(fullName: "Appalachian National Scenic Trail", description: "The Appalachian Trail is a 2,180+ mile long public footpath that traverses the scenic, wooded, pastoral, wild, and culturally resonant lands of the Appalachian Mountains. Conceived in 1921, built by private citizens, and completed in 1937, today the trail is managed by the National Park Service, US Forest Service, Appalachian Trail Conservancy, numerous state agencies and thousands of volunteers.", contacts: "304-535-6278", entranceFees: "0.00", operatingHours: "All Day", addresses: "Appalachian Trail Park Office, Harpers Ferry, WV 25425")
AllPark.create(fullName: "Appomattox Court House National Historical Park", description: "On April 9, 1865, the surrender of the Army of Northern Virginia in the McLean House in the village of Appomattox Court House, Virginia signaled the end of the nation's largest war. Two important questions about its future were answered. Could the nation survive a civil war intact, and would that nation exist without slavery? The answer to both was yes and a new nation was born.", contacts: "434-352-8987", entranceFees: "0.00", operatingHours: "9:00AM - 5:00PM", addresses: "239 George Peers Drive, Appomattox, VA 25422")
AllPark.create(fullName: "Arches National Park", description: "Visit Arches to discover a landscape of contrasting colors, land forms, and textures unlike any other in the world. The park has over 2,000 natural stone arches and hundreds of soaring pinnacles, massive rock fins, and giant balanced rocks. This red-rock wonderland will amaze you with its formations, refresh you with its trails, and inspire you with its sunsets.", contacts: "435-719-2299", entranceFees: "15.00", operatingHours: "All Day", addresses: "5 miles north of Moab, Utah, on US 191, Moab, UT 84532")
AllPark.create(fullName: "Arkansas Post National Memorial", description: "Located at the confluence of two rivers, Arkansas Post has served as a gathering place for many cultures throughout human history - it represents cultural cooperation, conflict, synthesis, and diversity.", contacts: "870-548-2207", entranceFees: "0.00", operatingHours: "7:00AM - Sunset", addresses: "1741 Old Post Road, Gillett, AR 72055")
AllPark.create(fullName: "Arlington House, The Robert E. Lee Memorial", description: "Arlington House is the nation’s memorial to Robert E. Lee. It honors him for specific reasons, including his role in promoting peace and reunion after the Civil War. In a larger sense it exists as a place of study and contemplation of the meaning of some of the most difficult aspects of American history: military service; sacrifice; citizenship; duty; loyalty; slavery and freedom.", contacts: "703-235-1530", entranceFees: "0.00", operatingHours: "9:00AM - 4:30PM", addresses: "Arlington National Cemetery, Arlington, VA 22211")
AllPark.create(fullName: "Assateague Island National Seashore", description: "Want to live on the edge? Visit a place recreated each day by ocean wind and waves. Life on Assateague Island has adapted to an existence on the move. Explore sandy beaches, salt marshes, maritime forests and coastal bays. Rest, relax, recreate and enjoy some time on the edge of the continent.", contacts: "410-641-1441", entranceFees: "10.00", operatingHours: "All Day", addresses: "7206 National Seashore Lane, Berlin, MD 21811")
AllPark.create(fullName: "Aztec Ruins National Monument", description: "Pueblo people describe this site as part of their migration journey. Today you can follow their ancient passageways to a distant time. Explore a 900-year old ancestral Pueblo Great House of over 400 masonry rooms. Look up and see original timbers holding up the roof. Search for the fingerprints of ancient workers in the mortar. Listen for an echo of ritual drums in the reconstructed Great Kiva.", contacts: "5053346174", entranceFees: "0.00", operatingHours: "8:00AM - 6:00PM", addresses: "725 Ruins Road, Aztec, NM 87410")
AllPark.create(fullName: "Badlands National Park", description: "The rugged beauty of the Badlands draws visitors from around the world. These striking geologic deposits contain one of the world’s richest fossil beds. Ancient horses and rhinos once roamed here. The park’s 244,000 acres protect an expanse of mixed-grass prairie where bison, bighorn sheep, prairie dogs, and black-footed ferrets live today.", contacts: "605-433-5361", entranceFees: "15.00", operatingHours: "All Day", addresses: "25216 Ben Reifel Road, Interior, SD 57750")
AllPark.create(fullName: "Baltimore-Washington Parkway", description: "This 29-mile highway connects Baltimore, MD and Washington, D.C. The parkway has carried visitors to and from the capital city since 1954.", contacts: "301-344-3948", entranceFees: "0.00", operatingHours: "All Day", addresses: "Baltimore Washington Parkway, Greenbelt, MD 20770")
AllPark.create(fullName: "Bandelier National Monument", description: "Bandelier National Monument protects over 33,000 acres of rugged but beautiful canyon and mesa country as well as evidence of a human presence here going back over 11,000 years. Petroglyphs, dwellings carved into the soft rock cliffs, and standing masonry walls pay tribute to the early days of a culture that still survives in the surrounding communities.", contacts: "505-672-3861", entranceFees: "15.00", operatingHours: "Sunrise to Sunset", addresses: "15 Entrance RD, Los Alamos, NM 87544")
AllPark.create(fullName: "Belmont-Paul Women's Equality National Monument", description: "Home to the National Woman's Party for more than 90 years, this was the epicenter of the struggle for women's rights. From this house in the shadow of the U.S. Capitol and Supreme Court, Alice Paul and the NWP developed innovative strategies and tactics to advocate for the Equal Rights Amendment and equality for women. President Barack Obama designated the national monument on April 12, 2016.", contacts: "202-543-2240", entranceFees: "0.00", operatingHours: "9:00AM - 5:00PM", addresses: "144 Constitution Ave NE, Washington, DC 20002")
AllPark.create(fullName: "Bent's Old Fort National Historic Site", description: "Bent's Old Fort National Historic Site features a reconstructed 1840s adobe fur trading post on the mountain branch of the Santa Fe Trail where traders, trappers, travelers, and the Cheyenne and Arapaho tribes came together in peaceful terms for trade. Today, living historians recreate the sights, sounds, and smells of the past with guided tours, demonstrations and special events.", contacts: "719-383-5010", entranceFees: "3.00", operatingHours: "8:00AM - 5:30PM", addresses: "35110 State Highway 194, La Junta, CO 81050")
AllPark.create(fullName: "Bering Land Bridge National Preserve", description: "Bering Land Bridge National Preserve lies at the continental crossroads that greatly influenced the distribution of life in the Western Hemisphere during the Pleistocene Epoch. It is a vital landscape for indigenous communities who depend on the land just as their ancestors did for many generations. It is a wild and ecologically healthy landscape unlike any other.", contacts: "800-471-2352", entranceFees: "0.00", operatingHours: "All Day", addresses: "214 Front St, Nome, AK 99762")
AllPark.create(fullName: "Big Bend National Park", description: "There is a place in Far West Texas where night skies are dark as coal and rivers carve temple-like canyons in ancient limestone. Here, at the end of the road, hundreds of bird species take refuge in a solitary mountain range surrounded by weather-beaten desert. Tenacious cactus bloom in sublime southwestern sun, and diversity of species is the best in the country. This magical place is Big Bend...", contacts: "432-477-2251", entranceFees: "12.00", operatingHours: "All Day", addresses: "1 Panther Junction, Big Bend National Park, TX 79834")
AllPark.create(fullName: "Big Cypress National Preserve", description: "The freshwaters of the Big Cypress Swamp, essential to the health of the neighboring Everglades, support the rich marine estuaries along Florida's southwest coast. Conserving over 729,000 acres of this vast swamp, Big Cypress National Preserve contains a mixture of tropical and temperate plant communities that are home to diverse wildlife, including the Endangered Florida panther.", contacts: "239-695-2000", entranceFees: "0.00", operatingHours: "All Day", addresses: "33100 Tamiami Trail East, Ochopee, FL 34141")
AllPark.create(fullName: "Big Hole National Battlefield", description: "On August 9, 1877 gun shots shattered a chilly dawn on a sleeping camp of Nez Perce. By the time the smoke cleared on August 10, almost 90 Nez Perce were dead along with 31 soldiers and volunteers. Big Hole National Battlefield was created to honor all who were there.", contacts: "406-689-3155", entranceFees: "0.00", operatingHours: "Sunrise to Sunset", addresses: "16425 Highway 43 West, Wisdom, MT 59761")
AllPark.create(fullName: "Big South Fork National River & Recreation Area", description: "Encompassing 125,000 acres of the Cumberland Plateau, Big South Fork National River and Recreation Area protects the free-flowing Big South Fork of the Cumberland River and its tributaries. The area boasts miles of scenic gorges and sandstone bluffs, is rich with natural and historic features and has been developed to provide visitors with a wide range of outdoor recreational activities.", contacts: "423-569-9778", entranceFees: "0.00", operatingHours: "All Day", addresses: "4564 Leatherwood Road, Oneida, TN 37841")
AllPark.create(fullName: "Big Thicket National Preserve", description: "Life of all types abounds in the Big Thicket. This national preserve protects the incredible diversity of life found where multiple habitats converge in southeast Texas. Hiking trails and waterways meander through nine different ecosystems, from longleaf pine forests to cypress-lined bayous. It is a place of discovery, a place to wander and explore, a place to marvel at the richness of nature.", contacts: "409-951-6700", entranceFees: "0.00", operatingHours: "All Day", addresses: "6102 FM 420, Kountze, TX 77625")
AllPark.create(fullName: "Bighorn Canyon National Recreation Area", description: "The vast, wild landscape of Bighorn Canyon National Recreation Area offers visitors unparalleled opportunities to immerse themselves in the natural world, and experience the wonders of this extraordinary place. With over 120,000 acres, one can find an astounding diversity in ecosystems, wildlife, and more than 10,000 years of human history to explore.", contacts: "307-548-5406", entranceFees: "0.00", operatingHours: "8:30AM - 4:30PM", addresses: "20 US Hwy 14A, Lovell, WY 82431")
AllPark.create(fullName: "Birmingham Civil Rights National Monument", description: "In 1963, images of snarling police dogs unleashed against non-violent protesters and of children being sprayed with high-pressure hoses appeared in print and television news around the world. These dramatic scenes of violent police aggression against civil rights protesters in Birmingham, Alabama were vivid examples of segregation and racial injustice in America.", contacts: "205-202-3757", entranceFees: "0.00", operatingHours: "10:00AM - 3:00PM", addresses: "1520 5th Avenue North, Birmingham, AL 35203")
AllPark.create(fullName: "Biscayne National Park", description: "Within sight of Miami, yet worlds away, Biscayne protects a rare combination of aquamarine waters, emerald islands, and fish-bejeweled coral reefs. Evidence of 10,000 years of human history is here too; from prehistoric tribes to shipwrecks, and pineapple farmers to presidents. For many, the park is a boating, fishing, and diving destination, while others enjoy a warm breeze and peaceful scenery.", contacts: "305-230-1144", entranceFees: "0.00", operatingHours: "All Day", addresses: "9700 SW 328th Street, Homestead, FL 33033")
AllPark.create(fullName: "Black Canyon Of The Gunnison National Park", description: "Big enough to be overwhelming, still intimate enough to feel the pulse of time, Black Canyon of the Gunnison exposes you to some of the steepest cliffs, oldest rock, and craggiest spires in North America. With two million years to work, the Gunnison River, along with the forces of weathering, has sculpted this vertical wilderness of rock, water, and sky.", contacts: "970-641-2337", entranceFees: "15.00", operatingHours: "All Day", addresses: "9800 Highway 347, Montrose, CO 81401")
AllPark.create(fullName: "Blackstone River Valley National Historical Park", description: "The Blackstone River powered America's entry into the Age of Industry. The success of Samuel Slater's cotton spinning mill in Pawtucket, RI touched off a chain reaction that changed how people worked and where they lived, and continues to reverberate across the nation to this day. Come visit and see how this revolution transformed the landscape of the Blackstone Valley and then the United States.", contacts: "401-521-7266", entranceFees: "0.00", operatingHours: "All Day", addresses: "67 Roosevelt Ave, Pawtucket, RI 02860")
AllPark.create(fullName: "Blue Ridge Parkway", description: "A Blue Ridge Parkway experience is unlike any other: a slow-paced and relaxing drive revealing stunning long-range vistas and close-up views of the rugged mountains and pastoral landscapes of the Appalachian Highlands. The Parkway meanders for 469 miles, protecting a diversity of plants and animals, and providing opportunities for enjoying all that makes this region of the country so special.", contacts: "828-348-3400", entranceFees: "0.00", operatingHours: "All Day", addresses: "Milepost 384, Asheville, NC 28803")
AllPark.create(fullName: "Bluestone National Scenic River", description: "The Bluestone River and the rugged and ancient gorge it has carved is a richly diverse and scenic area of the southern Appalachians. Bluestone National Scenic River is preserved as a living landscape that provides an unspoiled experience for visitors and a haven for a variety of plants and animals. The park protects a 10.5-mile section of the Bluestone River in southern West Virginia.", contacts: "304-465-0508", entranceFees: "0.00", operatingHours: "All Day", addresses: "3405 Pipestem Drive, Pipestem, WV 25979")
AllPark.create(fullName: "Booker T Washington National Monument", description: "Booker T. Washington was born a slave in April 1856 on the 207-acre farm of James Burroughs. After the Civil War, Washington became the first principal of Tuskegee Normal and Industrial School. Later as an adviser, author and orator, his past would influence his philosophies as the most influential African American of his era. Come explore his birthplace.", contacts: "540-721-2094", entranceFees: "0.00", operatingHours: "9:00AM - 5:00PM", addresses: "12130 Booker T. Washington Highway, Hardy, VA 24101")
AllPark.create(fullName: "Boston African American National Historic Site", description: "Centered on the north slope of Beacon Hill, the African American community of 19th century Boston led the city and the nation in the fight against slavery and injustice. These remarkable men and women, together with their allies, were leaders in the Abolition Movement, the Underground Railroad, the Civil War, and the early struggle for equal rights and education.", contacts: "617-742-5415", entranceFees: "0.00", operatingHours: "10:00AM - 4:00PM", addresses: "15 State Street, Boston, MA 02109")
AllPark.create(fullName: "Boston Harbor Islands National Recreation Area", description: ". . . where you can walk a Civil War-era fort, visit historic lighthouses, explore tide pools, hike lush trails, camp under the stars, or relax while fishing, picnicking or swimming-all within reach of downtown Boston. Youth programs, visitor services, research, wildlife management, and more are coordinated on the park's 34 islands and peninsulas by the Boston Harbor Islands Partnership.", contacts: "617-223-8666", entranceFees: "0.00", operatingHours: "All Day", addresses: "15 State Street, Boston, MA 02109")
AllPark.create(fullName: "Boston National Historical Park", description: "Discover how one city could be the Cradle of Liberty, site of the first major battle of American Revolution, and home to many who espoused that freedom can be extended to all.", contacts: "617-242-5601", entranceFees: "0.00", operatingHours: "9:00AM - 5:00PM", addresses: "21 Second Ave, Charlestown, MA 02129")